<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.1 (Python 3.6.9 on linux)" generated="20200508 23:04:18.939" rpa="false">
<suite id="s1" name="Pyats1" source="/home/thiago/Documentos/Code/Python/Networking/IOS/network-automation/pyats/robot-framework/pyats1.robot">
<test id="s1-t1" name="T1_Initialize">
<kw name="use testbed &quot;${testbed_1}&quot;" library="pyats.robot.pyATSRobot">
<doc>Load testbed YAML file and instantiate testbed object</doc>
<status status="PASS" starttime="20200508 23:04:19.506" endtime="20200508 23:04:19.532"></status>
</kw>
<doc>Loading 'testbed'</doc>
<status status="PASS" starttime="20200508 23:04:19.505" endtime="20200508 23:04:19.532" critical="yes"></status>
</test>
<test id="s1-t2" name="T1_CommonSetup">
<kw name="run testcase &quot;vlans_check.CommonSetup&quot;" library="pyats.robot.pyATSRobot">
<doc>The keyword allow to call any pyATS testcase by passing the full
python path of the testcase.</doc>
<msg timestamp="20200508 23:04:19.536" level="FAIL">ModuleNotFoundError: No module named 'vlans_check'</msg>
<status status="FAIL" starttime="20200508 23:04:19.533" endtime="20200508 23:04:19.536"></status>
</kw>
<doc>CommonSetup for vlans_check.py</doc>
<status status="FAIL" starttime="20200508 23:04:19.532" endtime="20200508 23:04:19.537" critical="yes">ModuleNotFoundError: No module named 'vlans_check'</status>
</test>
<status status="FAIL" starttime="20200508 23:04:18.940" endtime="20200508 23:04:19.538"></status>
</suite>
<statistics>
<total>
<stat pass="1" fail="1">Critical Tests</stat>
<stat pass="1" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="1" fail="1" id="s1" name="Pyats1">Pyats1</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200508 23:04:19.504" level="ERROR">Error in file '/home/thiago/Documentos/Code/Python/Networking/IOS/network-automation/pyats/robot-framework/pyats1.robot' on line 5: Importing test library '/home/thiago/Documentos/Code/Python/Networking/IOS/network-automation/pyats/robot-framework/vlans_check.py' failed: FileNotFoundError: [Errno 2] No such file or directory: 'cisco_ios_show_vlan.template'
Traceback (most recent call last):
  File "/home/thiago/Documentos/Code/Python/Networking/IOS/network-automation/pyats/robot-framework/vlans_check.py", line 8, in &lt;module&gt;
    template = open('cisco_ios_show_vlan.template')
PYTHONPATH:
  /usr/local/bin
  /usr/lib/python36.zip
  /usr/lib/python3.6
  /usr/lib/python3.6/lib-dynload
  /home/thiago/.local/lib/python3.6/site-packages
  /usr/local/lib/python3.6/dist-packages
  /usr/lib/python3/dist-packages</msg>
<msg timestamp="20200508 23:04:19.504" level="ERROR">Error in file '/home/thiago/Documentos/Code/Python/Networking/IOS/network-automation/pyats/robot-framework/pyats1.robot' on line 6: Test library 'connectivity_check_v2.py' does not exist.</msg>
</errors>
</robot>
